# Generated by Django 3.1.2 on 2020-10-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorship',
            old_name='mentor_id',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='mentorship',
            old_name='project_id',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Undefined')], default='f', max_length=9),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=12),
        ),
    ]
